.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

/* Handwritten function */
nonmatching entry, 0x34

glabel entry
    /* 1000 80000400 3C088002 */  lui        $t0, %hi(gSecureCallArr)
    /* 1004 80000404 2508BFC0 */  addiu      $t0, $t0, %lo(gSecureCallArr)
    /* 1008 80000408 3409C4A0 */  ori        $t1, $zero, 0xC4A0
  .L8000040C:
    /* 100C 8000040C 2129FFF8 */  addi       $t1, $t1, -0x8 /* handwritten instruction */
    /* 1010 80000410 AD000000 */  sw         $zero, 0x0($t0)
    /* 1014 80000414 AD000004 */  sw         $zero, 0x4($t0)
    /* 1018 80000418 1520FFFC */  bnez       $t1, .L8000040C
    /* 101C 8000041C 21080008 */   addi      $t0, $t0, 0x8 /* handwritten instruction */
    /* 1020 80000420 3C0A8000 */  lui        $t2, %hi(n64main)
    /* 1024 80000424 3C1D8002 */  lui        $sp, %hi(D_800244B0)
    /* 1028 80000428 254A19A0 */  addiu      $t2, $t2, %lo(n64main)
    /* 102C 8000042C 01400008 */  jr         $t2
    /* 1030 80000430 27BD44B0 */   addiu     $sp, $sp, %lo(D_800244B0)
endlabel entry
    /* 1034 80000434 00000000 */  nop
    /* 1038 80000438 00000000 */  nop
    /* 103C 8000043C 00000000 */  nop
    /* 1040 80000440 00000000 */  nop
    /* 1044 80000444 00000000 */  nop
    /* 1048 80000448 00000000 */  nop
    /* 104C 8000044C 00000000 */  nop
