.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

/* Handwritten function */
nonmatching osGetCount, 0xC

glabel osGetCount
    /* 4800 80003C00 40024800 */  mfc0       $v0, $9 /* handwritten instruction */
    /* 4804 80003C04 03E00008 */  jr         $ra
    /* 4808 80003C08 00000000 */   nop
endlabel osGetCount
    /* 480C 80003C0C 00000000 */  nop
