.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

/* Handwritten function */
nonmatching osGetIntMask, 0x60

glabel osGetIntMask
    /* 5900 80004D00 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 5904 80004D04 3042FF01 */  andi       $v0, $v0, 0xFF01
    /* 5908 80004D08 3C088002 */  lui        $t0, %hi(D_8001B0E0)
    /* 590C 80004D0C 2508B0E0 */  addiu      $t0, $t0, %lo(D_8001B0E0)
    /* 5910 80004D10 8D090000 */  lw         $t1, 0x0($t0)
    /* 5914 80004D14 2401FFFF */  addiu      $at, $zero, -0x1
    /* 5918 80004D18 01214026 */  xor        $t0, $t1, $at
    /* 591C 80004D1C 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 5920 80004D20 00481025 */  or         $v0, $v0, $t0
    /* 5924 80004D24 3C09A430 */  lui        $t1, %hi(D_A430000C)
    /* 5928 80004D28 8D29000C */  lw         $t1, %lo(D_A430000C)($t1)
    /* 592C 80004D2C 11200008 */  beqz       $t1, .L80004D50
    /* 5930 80004D30 3C088002 */   lui       $t0, %hi(D_8001B0E0)
    /* 5934 80004D34 2508B0E0 */  addiu      $t0, $t0, %lo(D_8001B0E0)
    /* 5938 80004D38 8D080000 */  lw         $t0, 0x0($t0)
    /* 593C 80004D3C 00084402 */  srl        $t0, $t0, 16
    /* 5940 80004D40 2401FFFF */  addiu      $at, $zero, -0x1
    /* 5944 80004D44 01014026 */  xor        $t0, $t0, $at
    /* 5948 80004D48 3108003F */  andi       $t0, $t0, 0x3F
    /* 594C 80004D4C 01284825 */  or         $t1, $t1, $t0
  .L80004D50:
    /* 5950 80004D50 00095400 */  sll        $t2, $t1, 16
    /* 5954 80004D54 004A1025 */  or         $v0, $v0, $t2
    /* 5958 80004D58 03E00008 */  jr         $ra
    /* 595C 80004D5C 00000000 */   nop
endlabel osGetIntMask
