.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

/* Handwritten function */
nonmatching osInvalDCache, 0xAC

glabel osInvalDCache
    /* 2CE0 800020E0 18A0001F */  blez       $a1, .L80002160
    /* 2CE4 800020E4 00000000 */   nop
    /* 2CE8 800020E8 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 2CEC 800020EC 00AB082B */  sltu       $at, $a1, $t3
    /* 2CF0 800020F0 1020001D */  beqz       $at, .L80002168
    /* 2CF4 800020F4 00000000 */   nop
    /* 2CF8 800020F8 00804025 */  or         $t0, $a0, $zero
    /* 2CFC 800020FC 00854821 */  addu       $t1, $a0, $a1
    /* 2D00 80002100 0109082B */  sltu       $at, $t0, $t1
    /* 2D04 80002104 10200016 */  beqz       $at, .L80002160
    /* 2D08 80002108 00000000 */   nop
    /* 2D0C 8000210C 310A000F */  andi       $t2, $t0, 0xF
    /* 2D10 80002110 11400007 */  beqz       $t2, .L80002130
    /* 2D14 80002114 2529FFF0 */   addiu     $t1, $t1, -0x10
    /* 2D18 80002118 010A4023 */  subu       $t0, $t0, $t2
    /* 2D1C 8000211C BD150000 */  cache      0x15, 0x0($t0) /* handwritten instruction */
    /* 2D20 80002120 0109082B */  sltu       $at, $t0, $t1
    /* 2D24 80002124 1020000E */  beqz       $at, .L80002160
    /* 2D28 80002128 00000000 */   nop
    /* 2D2C 8000212C 25080010 */  addiu      $t0, $t0, 0x10
  .L80002130:
    /* 2D30 80002130 312A000F */  andi       $t2, $t1, 0xF
    /* 2D34 80002134 11400006 */  beqz       $t2, .L80002150
    /* 2D38 80002138 00000000 */   nop
    /* 2D3C 8000213C 012A4823 */  subu       $t1, $t1, $t2
    /* 2D40 80002140 BD350010 */  cache      0x15, 0x10($t1) /* handwritten instruction */
    /* 2D44 80002144 0128082B */  sltu       $at, $t1, $t0
    /* 2D48 80002148 14200005 */  bnez       $at, .L80002160
    /* 2D4C 8000214C 00000000 */   nop
  .L80002150:
    /* 2D50 80002150 BD110000 */  cache      0x11, 0x0($t0) /* handwritten instruction */
    /* 2D54 80002154 0109082B */  sltu       $at, $t0, $t1
    /* 2D58 80002158 1420FFFD */  bnez       $at, .L80002150
    /* 2D5C 8000215C 25080010 */   addiu     $t0, $t0, 0x10
  .L80002160:
    /* 2D60 80002160 03E00008 */  jr         $ra
    /* 2D64 80002164 00000000 */   nop
  .L80002168:
    /* 2D68 80002168 3C088000 */  lui        $t0, 0x8000
    /* 2D6C 8000216C 010B4821 */  addu       $t1, $t0, $t3
    /* 2D70 80002170 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L80002174:
    /* 2D74 80002174 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 2D78 80002178 0109082B */  sltu       $at, $t0, $t1
    /* 2D7C 8000217C 1420FFFD */  bnez       $at, .L80002174
    /* 2D80 80002180 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 2D84 80002184 03E00008 */  jr         $ra
    /* 2D88 80002188 00000000 */   nop
endlabel osInvalDCache
    /* 2D8C 8000218C 00000000 */  nop
