.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

/* Handwritten function */
nonmatching osInvalICache, 0x74

glabel osInvalICache
    /* 2D90 80002190 18A00011 */  blez       $a1, .L800021D8
    /* 2D94 80002194 00000000 */   nop
    /* 2D98 80002198 240B4000 */  addiu      $t3, $zero, 0x4000
    /* 2D9C 8000219C 00AB082B */  sltu       $at, $a1, $t3
    /* 2DA0 800021A0 1020000F */  beqz       $at, .L800021E0
    /* 2DA4 800021A4 00000000 */   nop
    /* 2DA8 800021A8 00804025 */  or         $t0, $a0, $zero
    /* 2DAC 800021AC 00854821 */  addu       $t1, $a0, $a1
    /* 2DB0 800021B0 0109082B */  sltu       $at, $t0, $t1
    /* 2DB4 800021B4 10200008 */  beqz       $at, .L800021D8
    /* 2DB8 800021B8 00000000 */   nop
    /* 2DBC 800021BC 310A001F */  andi       $t2, $t0, 0x1F
    /* 2DC0 800021C0 2529FFE0 */  addiu      $t1, $t1, -0x20
    /* 2DC4 800021C4 010A4023 */  subu       $t0, $t0, $t2
  .L800021C8:
    /* 2DC8 800021C8 BD100000 */  cache      0x10, 0x0($t0) /* handwritten instruction */
    /* 2DCC 800021CC 0109082B */  sltu       $at, $t0, $t1
    /* 2DD0 800021D0 1420FFFD */  bnez       $at, .L800021C8
    /* 2DD4 800021D4 25080020 */   addiu     $t0, $t0, 0x20
  .L800021D8:
    /* 2DD8 800021D8 03E00008 */  jr         $ra
    /* 2DDC 800021DC 00000000 */   nop
  .L800021E0:
    /* 2DE0 800021E0 3C088000 */  lui        $t0, 0x8000
    /* 2DE4 800021E4 010B4821 */  addu       $t1, $t0, $t3
    /* 2DE8 800021E8 2529FFE0 */  addiu      $t1, $t1, -0x20
  .L800021EC:
    /* 2DEC 800021EC BD000000 */  cache      0x00, 0x0($t0) /* handwritten instruction */
    /* 2DF0 800021F0 0109082B */  sltu       $at, $t0, $t1
    /* 2DF4 800021F4 1420FFFD */  bnez       $at, .L800021EC
    /* 2DF8 800021F8 25080020 */   addiu     $t0, $t0, (0x80000020 & 0xFFFF)
    /* 2DFC 800021FC 03E00008 */  jr         $ra
    /* 2E00 80002200 00000000 */   nop
endlabel osInvalICache
    /* 2E04 80002204 00000000 */  nop
    /* 2E08 80002208 00000000 */  nop
    /* 2E0C 8000220C 00000000 */  nop
