.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

/* Handwritten function */
nonmatching osMapTLB, 0xB4

glabel osMapTLB
    /* 2740 80001B40 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 2744 80001B44 40840000 */  mtc0       $a0, $0 /* handwritten instruction */
    /* 2748 80001B48 40852800 */  mtc0       $a1, $5 /* handwritten instruction */
    /* 274C 80001B4C 8FA90014 */  lw         $t1, 0x14($sp)
    /* 2750 80001B50 2401FFFF */  addiu      $at, $zero, -0x1
    /* 2754 80001B54 11210004 */  beq        $t1, $at, .L80001B68
    /* 2758 80001B58 240C0001 */   addiu     $t4, $zero, 0x1
    /* 275C 80001B5C 240A001E */  addiu      $t2, $zero, 0x1E
    /* 2760 80001B60 10000002 */  b          .L80001B6C
    /* 2764 80001B64 00C93025 */   or        $a2, $a2, $t1
  .L80001B68:
    /* 2768 80001B68 240A001F */  addiu      $t2, $zero, 0x1F
  .L80001B6C:
    /* 276C 80001B6C 40865000 */  mtc0       $a2, $10 /* handwritten instruction */
    /* 2770 80001B70 2401FFFF */  addiu      $at, $zero, -0x1
    /* 2774 80001B74 10E10006 */  beq        $a3, $at, .L80001B90
    /* 2778 80001B78 00000000 */   nop
    /* 277C 80001B7C 00075982 */  srl        $t3, $a3, 6
    /* 2780 80001B80 016A5825 */  or         $t3, $t3, $t2
    /* 2784 80001B84 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
    /* 2788 80001B88 10000002 */  b          .L80001B94
    /* 278C 80001B8C 00000000 */   nop
  .L80001B90:
    /* 2790 80001B90 408C1000 */  mtc0       $t4, $2 /* handwritten instruction */
  .L80001B94:
    /* 2794 80001B94 8FAB0010 */  lw         $t3, 0x10($sp)
    /* 2798 80001B98 2401FFFF */  addiu      $at, $zero, -0x1
    /* 279C 80001B9C 11610006 */  beq        $t3, $at, .L80001BB8
    /* 27A0 80001BA0 00000000 */   nop
    /* 27A4 80001BA4 000B5982 */  srl        $t3, $t3, 6
    /* 27A8 80001BA8 016A5825 */  or         $t3, $t3, $t2
    /* 27AC 80001BAC 408B1800 */  mtc0       $t3, $3 /* handwritten instruction */
    /* 27B0 80001BB0 10000007 */  b          .L80001BD0
    /* 27B4 80001BB4 00000000 */   nop
  .L80001BB8:
    /* 27B8 80001BB8 408C1800 */  mtc0       $t4, $3 /* handwritten instruction */
    /* 27BC 80001BBC 2401FFFF */  addiu      $at, $zero, -0x1
    /* 27C0 80001BC0 14E10003 */  bne        $a3, $at, .L80001BD0
    /* 27C4 80001BC4 00000000 */   nop
    /* 27C8 80001BC8 3C0B8000 */  lui        $t3, (0x80000000 >> 16)
    /* 27CC 80001BCC 408B5000 */  mtc0       $t3, $10 /* handwritten instruction */
  .L80001BD0:
    /* 27D0 80001BD0 00000000 */  nop
    /* 27D4 80001BD4 42000002 */  tlbwi /* handwritten instruction */
    /* 27D8 80001BD8 00000000 */  nop
    /* 27DC 80001BDC 00000000 */  nop
    /* 27E0 80001BE0 00000000 */  nop
    /* 27E4 80001BE4 00000000 */  nop
    /* 27E8 80001BE8 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 27EC 80001BEC 03E00008 */  jr         $ra
    /* 27F0 80001BF0 00000000 */   nop
endlabel osMapTLB
    /* 27F4 80001BF4 00000000 */  nop
    /* 27F8 80001BF8 00000000 */  nop
    /* 27FC 80001BFC 00000000 */  nop
