.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

/* Handwritten function */
nonmatching osWritebackDCache, 0x74

glabel osWritebackDCache
    /* 2C60 80002060 18A00011 */  blez       $a1, .L800020A8
    /* 2C64 80002064 00000000 */   nop
    /* 2C68 80002068 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 2C6C 8000206C 00AB082B */  sltu       $at, $a1, $t3
    /* 2C70 80002070 1020000F */  beqz       $at, .L800020B0
    /* 2C74 80002074 00000000 */   nop
    /* 2C78 80002078 00804025 */  or         $t0, $a0, $zero
    /* 2C7C 8000207C 00854821 */  addu       $t1, $a0, $a1
    /* 2C80 80002080 0109082B */  sltu       $at, $t0, $t1
    /* 2C84 80002084 10200008 */  beqz       $at, .L800020A8
    /* 2C88 80002088 00000000 */   nop
    /* 2C8C 8000208C 310A000F */  andi       $t2, $t0, 0xF
    /* 2C90 80002090 2529FFF0 */  addiu      $t1, $t1, -0x10
    /* 2C94 80002094 010A4023 */  subu       $t0, $t0, $t2
  .L80002098:
    /* 2C98 80002098 BD190000 */  cache      0x19, 0x0($t0) /* handwritten instruction */
    /* 2C9C 8000209C 0109082B */  sltu       $at, $t0, $t1
    /* 2CA0 800020A0 1420FFFD */  bnez       $at, .L80002098
    /* 2CA4 800020A4 25080010 */   addiu     $t0, $t0, 0x10
  .L800020A8:
    /* 2CA8 800020A8 03E00008 */  jr         $ra
    /* 2CAC 800020AC 00000000 */   nop
  .L800020B0:
    /* 2CB0 800020B0 3C088000 */  lui        $t0, 0x8000
    /* 2CB4 800020B4 010B4821 */  addu       $t1, $t0, $t3
    /* 2CB8 800020B8 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L800020BC:
    /* 2CBC 800020BC BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 2CC0 800020C0 0109082B */  sltu       $at, $t0, $t1
    /* 2CC4 800020C4 1420FFFD */  bnez       $at, .L800020BC
    /* 2CC8 800020C8 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 2CCC 800020CC 03E00008 */  jr         $ra
    /* 2CD0 800020D0 00000000 */   nop
endlabel osWritebackDCache
    /* 2CD4 800020D4 00000000 */  nop
    /* 2CD8 800020D8 00000000 */  nop
    /* 2CDC 800020DC 00000000 */  nop
